import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <div>
            <img class="nav-img" src="./qudu-logo.svg" alt="" />
          </div>
          <div class="nav-title">AI Powered Code Review App</div>
        </nav>
        {children}
      </body>
    </html>
  )
}
